# Generated by Django 3.1.3 on 2020-11-26 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls1', '0003_answer_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='Book',
        ),
        migrations.DeleteModel(
            name='answer',
        ),
        migrations.AddField(
            model_name='read',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls1.book'),
        ),
    ]
